### ISSUE TITLE
🚔  Rename RandomsWithinClosedRange

### ISSUE THREAD

**Issue by johndpope** [phimage/RandomDistributionKit#1]
Ciao Eric,
running into some glitches compiling.
<img width="977" alt="screen shot 2017-07-06 at 9 44 27 am" src="https://user-images.githubusercontent.com/289994/27913975-be82a0e4-622f-11e7-86f0-72ab8518a15f.png">

I believe RandKit changed 
RandomWithinClosedRange -> 
RandomsWithinClosedRange

but updating this seems to create new bugs.
<img width="1195" alt="screen shot 2017-07-06 at 9 50 02 am" src="https://user-images.githubusercontent.com/289994/27914231-8094b76c-6230-11e7-9680-689dcfd5748d.png">

**Comment by phimage** [comment]
ok thanks
Do not hesitate to PR
